$siteRoot = "J:\Yishen-Mothership"
$pages = "$siteRoot\pages"

if (!(Test-Path $pages)) { mkdir $pages }

$tpl = @{
  "index.html" = "YISHEN GLOBAL — Sovereign AI & Global Supply Chain Network"
  "solutions.html" = "Industrial Solutions"
  "why-us.html" = "Why Choose YiShen Global"
  "resources.html" = "Technical Resources"
  "contact.html" = "Contact YiShen Global"
}

foreach ($p in $tpl.Keys) {
  $file = "$pages\$p"
  $html = @"
<!DOCTYPE html>
<html>
<head><meta charset='UTF-8'><title>$($tpl[$p])</title></head>
<body>
<h1>$($tpl[$p])</h1>
<p>Generated by YiShen Mothership Forge Engine</p>
</body>
</html>
"@
  Set-Content $file $html -Encoding UTF8
  Write-Host "FORGED: $p"
}
