name: "Sitemap Auto-Sync Protocol V5.0 MASTER"

# =========================================================
# 逻辑集成：[LEDGER_COLLISION], [PDF_INDEXING], [SEARCH_PING]
# 权限：Strategic Architecture Group / Yishen HQ
# =========================================================

on:
  push:
    branches:
      - main
    paths:
      - "**.html"           # 网页架构变动
      - "asset-ledger.json"  # 核心资产账本变动 (V5.0)
      - "sku-database.json"  # 兼容旧版数据库变动
      - "assets/docs/**.pdf" # 避税与合规协议变动
      - "generate_sitemap.py" # 逻辑脚本变动
  workflow_dispatch:         # 支持统帅手动强行发射索引

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: "Generate and Notify Sovereign Index"
    permissions:
      contents: write         # 赋予 Bot 写回仓库的物理主权

    steps:
      - name: "01_Checkout_Sovereign_Code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "02_Setup_Python_Environment"
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: "03_Execute_Custom_Generator"
        run: |
          # 执行 V5.0 脚本，将 asset-ledger.json 动态映射至 sitemap
          echo ">>> [SYSTEM_V5]: COLLIDING_ASSET_LEDGER_WITH_SITEMAP..."
          if [ -f "generate_sitemap.py" ]; then
            python generate_sitemap.py
          fi

      - name: "04_Generate_Global_Sitemap_XML"
        id: sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://yishenglobal.net/
          sitemap-format: xml
          path-to-root: .
          # [CRITICAL] 包含 PDF 协议索引：确保 Form E 和技术规格书能被 Google 嗅探
          include-pdf: true  
          additional-extensions: json, php
          exclude-files: "CNAME, README.md, vercel.json, .gitignore, link_fixer.py, deploy.sh, crawler-engine.js"

      - name: "05_Commit_and_Push_Sovereignty_Index"
        run: |
          git config --global user.name "Yishen-Sovereignty-Bot"
          git config --global user.email "bot@yishenglobal.net"
          
          # 对齐两个索引文件：sitemap.xml (全量扫描) 与 sovereign-index.xml (逻辑生成)
          git add sitemap.xml sovereign-index.xml
          
          # 物理检查：仅在索引发生实质改变时推送，[skip ci] 杜绝递归逻辑死循环
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore(sync): global sovereignty index V5.0 updated [skip ci]" && git push)

      - name: "06_Notify_Search_Engines"
        run: |
          echo ">>> SENDING_SOVEREIGN_PULSE_TO_GLOBAL_NODES..."
          # 向 Google 和 Bing 强制通报母舰最新的七大维度资产路径
          curl "https://www.google.com/ping?sitemap=https://yishenglobal.net/sitemap.xml"
          curl "https://www.google.com/ping?sitemap=https://yishenglobal.net/sovereign-index.xml"
          curl "https://www.bing.com/ping?sitemap=https://yishenglobal.net/sitemap.xml"
          echo ">>> [SUCCESS]: SEARCH_ENGINES_NOTIFIED."
